name: Build Cycles
description: 'Build Cycles'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "unirender_cycles > build_cycles"
  
    - name: Initialize Env
      id: init-env
      uses: Silverlan/common_actions/set_common_env_vars@main
      
    - name: Install prerequisites
      shell: bash
      run:   |
        sudo apt-get update
        sudo apt-get install cmake
        sudo apt-get install subversion
        sudo apt-get install python3.6

    - name: Download Cycles
      shell: bash
      run:   |
        git clone git://git.blender.org/cycles.git
        cd cycles
        git checkout b1882be6b1f2e27725ee672d87c5b6f8d6113eb1

    - name: Apply Modifications
      if: runner.os == 'Windows'
      shell: pwsh
      run:   |
        # We need to add the --allow-unsupported-compiler flag to a cycles CMake configuration file manually,
        # otherwise compilation will fail for newer versions of Visual Studio.
        $kernelCmakePath="./cycles/src/kernel/CMakeLists.txt"
        $unsupportedCompilerFlag = Select-String -Path "$kernelCmakePath" -Pattern '--allow-unsupported-compiler'
        if ($unsupportedCompilerFlag -eq $null) {
          # Only set the flag if it hasn't been set yet
          (Get-Content "$kernelCmakePath").replace('${CUDA_NVCC_FLAGS}', '${CUDA_NVCC_FLAGS} --allow-unsupported-compiler') | Set-Content "$kernelCmakePath"
        }

    - name: Apply Modifications
      if: runner.os == 'Linux'
      shell: bash
      run:   |
        # Building the cycles executable causes build errors. We don't need it, but unfortunately cycles doesn't provide us with a
        # way to disable it, so we'll have to make some changes to the CMake configuration file.
        sed -i -e 's/if(WITH_CYCLES_STANDALONE)/if(false)/g' "cycles/src/app/CMakeLists.txt"

    - name: Build Cycles
      shell: bash
      run:   |
        cd cycles
        make update
        make
        cd ../
        mkdir cmake-make
        cd cmake-make
        cmake ../cycles -G "Unix Makefiles" -DWITH_CYCLES_EMBREE=1 -DWITH_CYCLES_CUDA_BINARIES=1 -DWITH_CYCLES_DEVICE_CUDA=1 -DWITH_CYCLES_DEVICE_OPTIX=1 -DWITH_CYCLES_OPENCOLORIO=1 -DWITH_CYCLES_OPENIMAGEDENOISE=1 -DWITH_CYCLES_OPENSUBDIV=1 -DWITH_CYCLES_OPENVDB=1 -DWITH_CYCLES_USD=1
        cmake --build ./ --verbose

    - uses: Silverlan/common_actions/action_end@main
