name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
        with:
          cc_version: ${{ matrix.cc }}
          cxx_version: ${{ matrix.cxx }}
          
      - name: Build
        id: build
        uses: Silverlan/tmp_UniRender_Cycles_ci/github_actions/build@main
        with:
          root_dir: "${{ env.GA_ROOT_DIR }}"
          should_checkout: "0"
          dir: '.'
          build_shared: '1'
          
      - name: Create Release Files
        shell: bash
        run: |
          mkdir release
          mkdir release/lib
          rsync --mkpath ./libUniRender_Cycles.so release/modules/unirender/cycles/

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
